language: python
python:
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script: coverage run django-mtg-card-catalog/manage.py test
notifications:
  email: false
after_success: coveralls
