language: python
python:
  - "3.8.10"
services:
  - postgresql
addons:
  postgresql: "11"
env:
  global:
    - PGPORT=5433
install:
  - pip install -r requirements.in
  - pip install coveralls
before_script:
  - sudo psql -p 5433 -U postgres -c 'create database cardcatalog;'
script: coverage run manage.py test
notifications:
  email: false
after_success: coveralls
