language: python
python:
  - "3.8.10"
services:
  - postgresql
addons:
  postgresql: "11"
env:
  global:
    - PGPORT=5433
before_install:
  # Use trust instead of peer authentication:
  - >-
    sudo sed -i
    -e '/local.*peer/s/postgres/all/'
    -e 's/peer\|md5/trust/g'
    /etc/postgresql/13/main/pg_hba.conf
  # Restart the PostgreSQL service:
  - sudo service postgresql@13-main restart
install:
  - pip install -r requirements.in
  - pip install coveralls
before_script:
  - sudo psql -p 5433 -U postgres -c 'create database cardcatalog;'
script: coverage run manage.py test
notifications:
  email: false
after_success: coveralls
