language: python
python:
  - "3.6"

install:
  - pip install -r django-mtg-card-catalog/requirements.txt
  - pip install coveralls

script: coverage run django-mtg-card-catalog/manage.py test
notifications:
  email: false
after_success: coveralls
