# -*- coding: utf-8 -*-
TEST_SET_DATA = {
    'name': 'Test Set',
    'groupId': 1,
    'categoryId': 1,
    'abbreviation': 'TEST',
    'isSupplemental': True,
    'modifiedOn': '2018-10-25T13:07:27.753',
    'publishedOn': '2015-10-02T00:00:00'
}

TCG_EXPO_SET_DATA = {'name': 'Zendikar Expeditions', 'groupId': 1649, 'categoryId': 1, 'abbreviation': 'EXP',
                     'isSupplemental': True, 'modifiedOn': '2018-10-25T13:07:27.753',
                     'publishedOn': '2015-10-02T00:00:00'}

MEDIA_PROMOS_SET_DATA = {'abbreviation': 'MEDIA', 'publishedOn': '1999-01-02T00:00:00', 'groupId': 72, 'categoryId': 1,
                         'name': 'Media Promos', 'isSupplemental': True, 'modifiedOn': '2018-11-12T19:16:13.62'}

SEVENTH_EDITION_SET_DATA = {'groupId': 2, 'name': '7th Edition', 'abbreviation': '7ED', 'isSupplemental': False,
                            'publishedOn': '2001-04-11T00:00:00', 'modifiedOn': '2019-03-31T16:41:20.503',
                            'categoryId': 1}

TENTH_EDITION_SET_DATA = {'groupId': 1, 'name': '10th Edition', 'abbreviation': '10E', 'isSupplemental': False,
                          'publishedOn': '2007-07-13T00:00:00', 'modifiedOn': '2019-04-04T17:47:05.71', 'categoryId': 1}

MISHRAS_FACTORY_FALL_TCG_DATA = {'name': "Mishra's Factory (Fall)", 'categoryId': 1, 'groupId': 8,
                                 'modifiedOn': '2016-12-06T15:17:58.05', 'productId': 77295,
                                 'url': 'https://store.tcgplayer.com/magic/antiquities/mishras-factory-fall',
                                 'imageUrl': 'https://6d4be195623157e28848-7697ece4918e0a73861de0eb37d08968.ssl.cf1.rackcdn.com/77295_200w.jpg',
                                 'cleanName': 'Mishras Factory Fall'}

PLAINS_VARIANT_TCG_DATA = {'name': 'Plains (251) - Full Art', 'categoryId': 1, 'groupId': 1645,
                           'modifiedOn': '2018-05-24T18:15:33.68', 'productId': 104402,
                           'url': 'https://store.tcgplayer.com/magic/battle-for-zendikar/plains-251-full-art',
                           'imageUrl': 'https://6d4be195623157e28848-7697ece4918e0a73861de0eb37d08968.ssl.cf1.rackcdn.com/104402_200w.jpg',
                           'cleanName': 'Plains 251 Full Art'}

SDCC_GIDEON_TCG_DATA = {'name': 'Gideon, Ally of Zendikar SDCC 2016 EXCLUSIVE',
                        'cleanName': 'Gideon Ally of Zendikar SDCC 2016 EXCLUSIVE',
                        'modifiedOn': '2017-03-16T19:33:20.11',
                        'imageUrl': 'https://6d4be195623157e28848-7697ece4918e0a73861de0eb37d08968.ssl.cf1.rackcdn.com/120963_200w.jpg',
                        'categoryId': 1,
                        'url': 'https://store.tcgplayer.com/magic/media-promos/gideon-ally-of-zendikar-sdcc-2016-exclusive',
                        'groupId': 72, 'productId': 120963}

CURATOR_TCG_DATA = {
    'imageUrl': 'https://6d4be195623157e28848-7697ece4918e0a73861de0eb37d08968.ssl.cf1.rackcdn.com/179080_200w.jpg',
    'productId': 179080, 'categoryId': 1, 'groupId': 72, 'modifiedOn': '2018-10-30T14:00:40.003',
    'cleanName': 'Curator of Mysteries', 'name': 'Curator of Mysteries',
    'url': 'https://store.tcgplayer.com/magic/media-promos/curator-of-mysteries'
}

TCG_EXPO_CARD_LIST = [
    {'name': 'Arid Mesa', 'groupId': 1649, 'categoryId': 1,
     'url': 'https://store.tcgplayer.com/magic/zendikar-expeditions/arid-mesa',
     'imageUrl': 'https://6d4be195623157e28848-7697ece4918e0a73861de0eb37d08968.ssl.cf1.rackcdn.com/104306_200w.jpg',
     'productId': 104306, 'cleanName': 'Arid Mesa', 'modifiedOn': '2018-09-04T17:15:45.61'},
    {'name': 'Steam Vents', 'groupId': 1649, 'categoryId': 1,
     'url': 'https://store.tcgplayer.com/magic/zendikar-expeditions/steam-vents',
     'imageUrl': 'https://6d4be195623157e28848-7697ece4918e0a73861de0eb37d08968.ssl.cf1.rackcdn.com/104307_200w.jpg',
     'productId': 104307, 'cleanName': 'Steam Vents', 'modifiedOn': '2018-04-24T16:13:37.543'},
]

LLANOWAR_ELVES_SCRYFALL_DATA = {"object": "card", "id": "73542493-cd0b-4bb7-a5b8-8f889c76e4d6",
                                "oracle_id": "68954295-54e3-4303-a6bc-fc4547a4e3a3", "multiverse_ids": [450261],
                                "mtgo_id": 68161, "tcgplayer_id": 168646, "name": "Llanowar Elves", "lang": "en",
                                "uri": "https://api.scryfall.com/cards/73542493-cd0b-4bb7-a5b8-8f889c76e4d6",
                                "scryfall_uri": "https://scryfall.com/card/m19/314/llanowar-elves?utm_source=api",
                                "layout": "normal", "highres_image": True, "image_uris": {
        "small": "https://img.scryfall.com/cards/small/en/m19/314.jpg?1531860934",
        "normal": "https://img.scryfall.com/cards/normal/en/m19/314.jpg?1531860934",
        "large": "https://img.scryfall.com/cards/large/en/m19/314.jpg?1531860934",
        "png": "https://img.scryfall.com/cards/png/en/m19/314.png?1531860934",
        "art_crop": "https://img.scryfall.com/cards/art_crop/en/m19/314.jpg?1531860934",
        "border_crop": "https://img.scryfall.com/cards/border_crop/en/m19/314.jpg?1531860934"}, "mana_cost": "{G}",
                                "cmc": 1.0, "type_line": "Creature — Elf Druid", "oracle_text": "{T}: Add {G}.",
                                "power": "1", "toughness": "1", "colors": ["G"], "color_identity": ["G"],
                                "legalities": {"standard": "legal", "future": "legal", "frontier": "legal",
                                               "modern": "legal", "legacy": "legal", "pauper": "legal",
                                               "vintage": "legal", "penny": "not_legal", "commander": "legal",
                                               "1v1": "legal", "duel": "legal", "brawl": "legal"}, "reserved": False,
                                "foil": False, "nonfoil": True, "oversized": False, "reprint": True, "set": "m19",
                                "set_name": "Core Set 2019", "set_uri": "https://api.scryfall.com/sets/m19",
                                "set_search_uri": "https://api.scryfall.com/cards/search?order=set\u0026q=e%3Am19\u0026unique=prints",
                                "scryfall_set_uri": "https://scryfall.com/sets/m19?utm_source=api",
                                "rulings_uri": "https://api.scryfall.com/cards/73542493-cd0b-4bb7-a5b8-8f889c76e4d6/rulings",
                                "prints_search_uri": "https://api.scryfall.com/cards/search?order=set\u0026q=%21%E2%80%9CLlanowar+Elves%E2%80%9D+include%3Aextras\u0026unique=prints",
                                "collector_number": "314", "digital": False, "rarity": "common",
                                "flavor_text": "As patient and generous as life, as harsh and merciless as nature.",
                                "illustration_id": "82c0ea68-cf37-41ec-aec7-123e8e9f05d3", "artist": "Chris Rahn",
                                "frame": "2015", "full_art": False, "border_color": "black", "timeshifted": False,
                                "colorshifted": False, "futureshifted": False, "story_spotlight": False,
                                "edhrec_rank": 120, "related_uris": {
        "gatherer": "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=450261",
        "tcgplayer_decks": "https://decks.tcgplayer.com/magic/deck/search?contains=Llanowar+Elves\u0026page=1\u0026partner=Scryfall\u0026utm_campaign=affiliate\u0026utm_medium=scryfall\u0026utm_source=scryfall",
        "edhrec": "http://edhrec.com/route/?cc=Llanowar+Elves",
        "mtgtop8": "http://mtgtop8.com/search?MD_check=1\u0026SB_check=1\u0026cards=Llanowar+Elves"}}

FLIP_BOLAS_SCRYFALL_DATA = {"object": "card", "id": "7b215968-93a6-4278-ac61-4e3e8c3c3943",
                            "oracle_id": "55e4b27e-5447-4fc2-8cae-a03e344600c6", "multiverse_ids": [447354, 447355],
                            "mtgo_id": 68597, "tcgplayer_id": 168740,
                            "name": "Nicol Bolas, the Ravager // Nicol Bolas, the Arisen", "lang": "en",
                            "uri": "https://api.scryfall.com/cards/7b215968-93a6-4278-ac61-4e3e8c3c3943",
                            "scryfall_uri": "https://scryfall.com/card/m19/218/nicol-bolas-the-ravager-nicol-bolas-the-arisen?utm_source=api",
                            "layout": "transform", "highres_image": True, "cmc": 4.0,
                            "type_line": "Legendary Creature — Elder Dragon // Legendary Planeswalker — Bolas",
                            "color_identity": ["B", "R", "U"], "card_faces": [
        {"object": "card_face", "name": "Nicol Bolas, the Ravager", "mana_cost": "{1}{U}{B}{R}",
         "type_line": "Legendary Creature — Elder Dragon",
         "oracle_text": "Flying\nWhen Nicol Bolas, the Ravager enters the battlefield, each opponent discards a card.\n{4}{U}{B}{R}: Exile Nicol Bolas, the Ravager, then return him to the battlefield transformed under his owner's control. Activate this ability only any time you could cast a sorcery.",
         "colors": ["B", "R", "U"], "power": "4", "toughness": "4", "artist": "Svetlin Velinov",
         "illustration_id": "54fcf679-5332-4614-999d-7e0dbafbd116",
         "image_uris": {"small": "https://img.scryfall.com/cards/small/en/m19/218a.jpg?1531451175",
                        "normal": "https://img.scryfall.com/cards/normal/en/m19/218a.jpg?1531451175",
                        "large": "https://img.scryfall.com/cards/large/en/m19/218a.jpg?1531451175",
                        "png": "https://img.scryfall.com/cards/png/en/m19/218a.png?1531451175",
                        "art_crop": "https://img.scryfall.com/cards/art_crop/en/m19/218a.jpg?1531451175",
                        "border_crop": "https://img.scryfall.com/cards/border_crop/en/m19/218a.jpg?1531451175"}},
        {"object": "card_face", "name": "Nicol Bolas, the Arisen", "mana_cost": "",
         "type_line": "Legendary Planeswalker — Bolas",
         "oracle_text": "+2: Draw two cards.\n−3: Nicol Bolas, the Arisen deals 10 damage to target creature or planeswalker.\n−4: Put target creature or planeswalker card from a graveyard onto the battlefield under your control.\n−12: Exile all but the bottom card of target player's library.",
         "colors": ["B", "R", "U"], "color_indicator": ["B", "R", "U"], "loyalty": "7", "artist": "Svetlin Velinov",
         "illustration_id": "98df1d4c-6b8a-4336-8df3-7bc560a5d2c0",
         "image_uris": {"small": "https://img.scryfall.com/cards/small/en/m19/218b.jpg?1531451175",
                        "normal": "https://img.scryfall.com/cards/normal/en/m19/218b.jpg?1531451175",
                        "large": "https://img.scryfall.com/cards/large/en/m19/218b.jpg?1531451175",
                        "png": "https://img.scryfall.com/cards/png/en/m19/218b.png?1531451175",
                        "art_crop": "https://img.scryfall.com/cards/art_crop/en/m19/218b.jpg?1531451175",
                        "border_crop": "https://img.scryfall.com/cards/border_crop/en/m19/218b.jpg?1531451175"}}],
                            "legalities": {"standard": "legal", "future": "legal", "frontier": "legal",
                                           "modern": "legal", "legacy": "legal", "pauper": "not_legal",
                                           "vintage": "legal", "penny": "not_legal", "commander": "legal",
                                           "1v1": "legal", "duel": "legal", "brawl": "legal"}, "reserved": False,
                            "foil": True, "nonfoil": True, "oversized": False, "reprint": False, "set": "m19",
                            "set_name": "Core Set 2019", "set_uri": "https://api.scryfall.com/sets/m19",
                            "set_search_uri": "https://api.scryfall.com/cards/search?order=set\u0026q=e%3Am19\u0026unique=prints",
                            "scryfall_set_uri": "https://scryfall.com/sets/m19?utm_source=api",
                            "rulings_uri": "https://api.scryfall.com/cards/7b215968-93a6-4278-ac61-4e3e8c3c3943/rulings",
                            "prints_search_uri": "https://api.scryfall.com/cards/search?order=set\u0026q=%21%E2%80%9CNicol+Bolas%2C+the+Ravager+%2F%2F+Nicol+Bolas%2C+the+Arisen%E2%80%9D+include%3Aextras\u0026unique=prints",
                            "collector_number": "218", "digital": False, "rarity": "mythic",
                            "artist": "Svetlin Velinov", "frame": "2015", "full_art": False, "border_color": "black",
                            "timeshifted": False, "colorshifted": False, "futureshifted": False,
                            "story_spotlight": False, "edhrec_rank": 1576, "related_uris": {
        "gatherer": "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=447354",
        "tcgplayer_decks": "https://decks.tcgplayer.com/magic/deck/search?contains=Nicol+Bolas%2C+the+Ravager\u0026page=1\u0026partner=Scryfall\u0026utm_campaign=affiliate\u0026utm_medium=scryfall\u0026utm_source=scryfall",
        "edhrec": "http://edhrec.com/route/?cc=Nicol+Bolas%2C+the+Ravager",
        "mtgtop8": "http://mtgtop8.com/search?MD_check=1\u0026SB_check=1\u0026cards=Nicol+Bolas%2C+the+Ravager"}}

TURN_BURN_SCRYFALL_DATA = {"object": "card", "id": "01ce2601-ae94-4ab5-bbd2-65f47281ca28",
                           "oracle_id": "41841bbf-1c51-494b-b299-c997cce88e44", "multiverse_ids": [456235],
                           "name": "Turn // Burn", "lang": "en",
                           "uri": "https://api.scryfall.com/cards/01ce2601-ae94-4ab5-bbd2-65f47281ca28",
                           "scryfall_uri": "https://scryfall.com/card/gk1/45/turn-burn?utm_source=api",
                           "layout": "split", "highres_image": True, "image_uris": {
        "small": "https://img.scryfall.com/cards/small/front/0/1/01ce2601-ae94-4ab5-bbd2-65f47281ca28.jpg?1541002895",
        "normal": "https://img.scryfall.com/cards/normal/front/0/1/01ce2601-ae94-4ab5-bbd2-65f47281ca28.jpg?1541002895",
        "large": "https://img.scryfall.com/cards/large/front/0/1/01ce2601-ae94-4ab5-bbd2-65f47281ca28.jpg?1541002895",
        "png": "https://img.scryfall.com/cards/png/front/0/1/01ce2601-ae94-4ab5-bbd2-65f47281ca28.png?1541002895",
        "art_crop": "https://img.scryfall.com/cards/art_crop/front/0/1/01ce2601-ae94-4ab5-bbd2-65f47281ca28.jpg?1541002895",
        "border_crop": "https://img.scryfall.com/cards/border_crop/front/0/1/01ce2601-ae94-4ab5-bbd2-65f47281ca28.jpg?1541002895"},
                           "mana_cost": "{2}{U} // {1}{R}", "cmc": 5.0, "type_line": "Instant // Instant",
                           "colors": ["R", "U"], "color_identity": ["R", "U"], "card_faces": [
        {"object": "card_face", "name": "Turn", "mana_cost": "{2}{U}", "type_line": "Instant",
         "oracle_text": "Until end of turn, target creature loses all abilities and becomes a red Weird with base power and toughness 0/1.\nFuse (You may cast one or both halves of this card from your hand.)",
         "watermark": "izzet"}, {"object": "card_face", "name": "Burn", "mana_cost": "{1}{R}", "type_line": "Instant",
                                 "oracle_text": "Burn deals 2 damage to any target.\nFuse (You may cast one or both halves of this card from your hand.)"}],
                           "legalities": {"standard": "not_legal", "future": "not_legal", "frontier": "not_legal",
                                          "modern": "legal", "legacy": "legal", "pauper": "not_legal",
                                          "vintage": "legal", "penny": "legal", "commander": "legal", "1v1": "legal",
                                          "duel": "legal", "brawl": "not_legal"}, "reserved": False, "foil": False,
                           "nonfoil": True, "oversized": False, "reprint": True, "set": "gk1",
                           "set_name": "GRN Guild Kit", "set_uri": "https://api.scryfall.com/sets/gk1",
                           "set_search_uri": "https://api.scryfall.com/cards/search?order=set\u0026q=e%3Agk1\u0026unique=prints",
                           "scryfall_set_uri": "https://scryfall.com/sets/gk1?utm_source=api",
                           "rulings_uri": "https://api.scryfall.com/cards/01ce2601-ae94-4ab5-bbd2-65f47281ca28/rulings",
                           "prints_search_uri": "https://api.scryfall.com/cards/search?order=set\u0026q=%21%E2%80%9CTurn+%2F%2F+Burn%E2%80%9D+include%3Aextras\u0026unique=prints",
                           "collector_number": "45", "digital": False, "rarity": "uncommon",
                           "illustration_id": "6f292968-be9f-469f-9491-f455c57a5149", "artist": "Ryan Barger",
                           "frame": "2015", "full_art": False, "border_color": "black", "timeshifted": False,
                           "colorshifted": False, "futureshifted": False, "story_spotlight": False, "edhrec_rank": 3933,
                           "related_uris": {
                               "gatherer": "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=456235",
                               "tcgplayer_decks": "https://decks.tcgplayer.com/magic/deck/search?contains=Turn+%2F%2F+Burn\u0026page=1\u0026partner=Scryfall\u0026utm_campaign=affiliate\u0026utm_medium=scryfall\u0026utm_source=scryfall",
                               "edhrec": "http://edhrec.com/route/?cc=Turn",
                               "mtgtop8": "http://mtgtop8.com/search?MD_check=1\u0026SB_check=1\u0026cards=Turn+%2F%2F+Burn"}}

BFM_LEFT_SCRYFALL_DATA = {"object": "card", "id": "a9f9c279-e382-4feb-9575-196e7cf5d7dc",
                          "oracle_id": "8fd7503b-e722-49a7-a8ac-786e7354bc95", "multiverse_ids": [9780],
                          "name": "B.F.M. (Big Furry Monster)", "lang": "en",
                          "uri": "https://api.scryfall.com/cards/a9f9c279-e382-4feb-9575-196e7cf5d7dc",
                          "scryfall_uri": "https://scryfall.com/card/ugl/28/bfm-(big-furry-monster)?utm_source=api",
                          "layout": "normal", "highres_image": True,
                          "image_uris": {"small": "https://img.scryfall.com/cards/small/en/ugl/28.jpg?1525888540",
                                         "normal": "https://img.scryfall.com/cards/normal/en/ugl/28.jpg?1525888540",
                                         "large": "https://img.scryfall.com/cards/large/en/ugl/28.jpg?1525888540",
                                         "png": "https://img.scryfall.com/cards/png/en/ugl/28.png?1525888540",
                                         "art_crop": "https://img.scryfall.com/cards/art_crop/en/ugl/28.jpg?1525888540",
                                         "border_crop": "https://img.scryfall.com/cards/border_crop/en/ugl/28.jpg?1525888540"},
                          "mana_cost": "{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}", "cmc": 15.0,
                          "type_line": "Creature — The Biggest, Baddest, Nastiest,",
                          "oracle_text": "You must cast both B.F.M. cards to put\nleaves the battlefield, sacrifice the other.\nB.F.M. can't be blocked except by three or",
                          "colors": ["B"], "color_identity": ["B"], "all_parts": [
        {"object": "related_card", "id": "a9f9c279-e382-4feb-9575-196e7cf5d7dc", "name": "B.F.M. (Big Furry Monster)",
         "uri": "https://api.scryfall.com/cards/ugl/28"},
        {"object": "related_card", "id": "d15c6375-2e4e-47f7-88e1-d90794e7f724", "name": "B.F.M. (Big Furry Monster)",
         "uri": "https://api.scryfall.com/cards/ugl/29"}],
                          "legalities": {"standard": "not_legal", "future": "not_legal", "frontier": "not_legal",
                                         "modern": "not_legal", "legacy": "not_legal", "pauper": "not_legal",
                                         "vintage": "not_legal", "penny": "not_legal", "commander": "not_legal",
                                         "1v1": "not_legal", "duel": "not_legal", "brawl": "not_legal"},
                          "reserved": False, "foil": False, "nonfoil": True, "oversized": False, "reprint": False,
                          "set": "ugl", "set_name": "Unglued", "set_uri": "https://api.scryfall.com/sets/ugl",
                          "set_search_uri": "https://api.scryfall.com/cards/search?order=set\u0026q=e%3Augl\u0026unique=prints",
                          "scryfall_set_uri": "https://scryfall.com/sets/ugl?utm_source=api",
                          "rulings_uri": "https://api.scryfall.com/cards/a9f9c279-e382-4feb-9575-196e7cf5d7dc/rulings",
                          "prints_search_uri": "https://api.scryfall.com/cards/search?order=set\u0026q=%21%E2%80%9CB.F.M.+%28Big+Furry+Monster%29%E2%80%9D+include%3Aextras\u0026unique=prints",
                          "collector_number": "28", "digital": False, "rarity": "rare",
                          "flavor_text": "\"It was big. Really, really big. No, bigger No, more. Look, we're talking krakens and",
                          "illustration_id": "604f7df7-c364-444a-9224-b7a952aa8512", "artist": "Douglas Shuler",
                          "frame": "1997", "full_art": False, "border_color": "silver", "timeshifted": False,
                          "colorshifted": False, "futureshifted": False, "story_spotlight": False, "related_uris": {
        "gatherer": "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9780",
        "tcgplayer_decks": "https://decks.tcgplayer.com/magic/deck/search?contains=B.F.M.+%28Big+Furry+Monster%29\u0026page=1\u0026partner=Scryfall\u0026utm_campaign=affiliate\u0026utm_medium=scryfall\u0026utm_source=scryfall",
        "edhrec": "http://edhrec.com/route/?cc=B.F.M.+%28Big+Furry+Monster%29",
        "mtgtop8": "http://mtgtop8.com/search?MD_check=1\u0026SB_check=1\u0026cards=B.F.M.+%28Big+Furry+Monster%29"}}

BFM_RIGHT_SCRYFALL_DATA = {"object": "card", "id": "d15c6375-2e4e-47f7-88e1-d90794e7f724",
                           "oracle_id": "d0bd00f2-91bb-4c9c-a8e7-f8aeadc0bbb9", "multiverse_ids": [9844],
                           "name": "B.F.M. (Big Furry Monster)", "lang": "en",
                           "uri": "https://api.scryfall.com/cards/d15c6375-2e4e-47f7-88e1-d90794e7f724",
                           "scryfall_uri": "https://scryfall.com/card/ugl/29/bfm-(big-furry-monster)?utm_source=api",
                           "layout": "normal", "highres_image": True,
                           "image_uris": {"small": "https://img.scryfall.com/cards/small/en/ugl/29.jpg?1525888555",
                                          "normal": "https://img.scryfall.com/cards/normal/en/ugl/29.jpg?1525888555",
                                          "large": "https://img.scryfall.com/cards/large/en/ugl/29.jpg?1525888555",
                                          "png": "https://img.scryfall.com/cards/png/en/ugl/29.png?1525888555",
                                          "art_crop": "https://img.scryfall.com/cards/art_crop/en/ugl/29.jpg?1525888555",
                                          "border_crop": "https://img.scryfall.com/cards/border_crop/en/ugl/29.jpg?1525888555"},
                           "mana_cost": "{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}", "cmc": 15.0,
                           "type_line": "Scariest Creature You’ll Ever See",
                           "oracle_text": "B.F.M. onto the battlefield. If one B.F.M. card\nmore creatures.",
                           "power": "99", "toughness": "99", "colors": ["B"], "color_identity": ["B"], "all_parts": [
        {"object": "related_card", "id": "a9f9c279-e382-4feb-9575-196e7cf5d7dc", "name": "B.F.M. (Big Furry Monster)",
         "uri": "https://api.scryfall.com/cards/ugl/28"},
        {"object": "related_card", "id": "d15c6375-2e4e-47f7-88e1-d90794e7f724", "name": "B.F.M. (Big Furry Monster)",
         "uri": "https://api.scryfall.com/cards/ugl/29"}],
                           "legalities": {"standard": "not_legal", "future": "not_legal", "frontier": "not_legal",
                                          "modern": "not_legal", "legacy": "not_legal", "pauper": "not_legal",
                                          "vintage": "not_legal", "penny": "not_legal", "commander": "not_legal",
                                          "1v1": "not_legal", "duel": "not_legal", "brawl": "not_legal"},
                           "reserved": False, "foil": False, "nonfoil": True, "oversized": False, "reprint": False,
                           "set": "ugl", "set_name": "Unglued", "set_uri": "https://api.scryfall.com/sets/ugl",
                           "set_search_uri": "https://api.scryfall.com/cards/search?order=set\u0026q=e%3Augl\u0026unique=prints",
                           "scryfall_set_uri": "https://scryfall.com/sets/ugl?utm_source=api",
                           "rulings_uri": "https://api.scryfall.com/cards/d15c6375-2e4e-47f7-88e1-d90794e7f724/rulings",
                           "prints_search_uri": "https://api.scryfall.com/cards/search?order=set\u0026q=%21%E2%80%9CB.F.M.+%28Big+Furry+Monster%29%E2%80%9D+include%3Aextras\u0026unique=prints",
                           "collector_number": "29", "digital": False, "rarity": "rare",
                           "flavor_text": "than that. Even bigger. Keep going. More. dreadnoughts for jewelry. It was big!\" —Arna Kennerüd, skyknight",
                           "illustration_id": "c85bd9c9-2a73-4e76-8c58-5903134b674d", "artist": "Douglas Shuler",
                           "frame": "1997", "full_art": False, "border_color": "silver", "timeshifted": False,
                           "colorshifted": False, "futureshifted": False, "story_spotlight": False, "related_uris": {
        "gatherer": "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9844",
        "tcgplayer_decks": "https://decks.tcgplayer.com/magic/deck/search?contains=B.F.M.+%28Big+Furry+Monster%29\u0026page=1\u0026partner=Scryfall\u0026utm_campaign=affiliate\u0026utm_medium=scryfall\u0026utm_source=scryfall",
        "edhrec": "http://edhrec.com/route/?cc=B.F.M.+%28Big+Furry+Monster%29",
        "mtgtop8": "http://mtgtop8.com/search?MD_check=1\u0026SB_check=1\u0026cards=B.F.M.+%28Big+Furry+Monster%29"}}

RUMORS_SCRYFALL_DATA = {"object": "card", "id": "cb3587b9-e727-4f37-b4d6-1baa7316262f",
                        "oracle_id": "38bcba8b-2838-4ac8-9976-f9ccaa94fdba", "multiverse_ids": [439454],
                        "tcgplayer_id": 153145, "name": "\"Rumors of My Death . . .\"", "lang": "en",
                        "uri": "https://api.scryfall.com/cards/cb3587b9-e727-4f37-b4d6-1baa7316262f",
                        "scryfall_uri": "https://scryfall.com/card/ust/65/rumors-of-my-death-?utm_source=api",
                        "layout": "normal", "highres_image": True,
                        "image_uris": {"small": "https://img.scryfall.com/cards/small/en/ust/65.jpg?1522206647",
                                       "normal": "https://img.scryfall.com/cards/normal/en/ust/65.jpg?1522206647",
                                       "large": "https://img.scryfall.com/cards/large/en/ust/65.jpg?1522206647",
                                       "png": "https://img.scryfall.com/cards/png/en/ust/65.png?1522206647",
                                       "art_crop": "https://img.scryfall.com/cards/art_crop/en/ust/65.jpg?1522206647",
                                       "border_crop": "https://img.scryfall.com/cards/border_crop/en/ust/65.jpg?1522206647"},
                        "mana_cost": "{2}{B}", "cmc": 3.0, "type_line": "Enchantment",
                        "oracle_text": "{3}{B}, Exile a permanent you control with a League of Dastardly Doom watermark: Return a permanent card with a League of Dastardly Doom watermark from your graveyard to the battlefield.",
                        "colors": ["B"], "color_identity": ["B"],
                        "legalities": {"standard": "not_legal", "future": "not_legal", "frontier": "not_legal",
                                       "modern": "not_legal", "legacy": "not_legal", "pauper": "not_legal",
                                       "vintage": "not_legal", "penny": "not_legal", "commander": "not_legal",
                                       "1v1": "not_legal", "duel": "not_legal", "brawl": "not_legal"},
                        "reserved": False, "foil": True, "nonfoil": True, "oversized": False, "reprint": False,
                        "set": "ust", "set_name": "Unstable", "set_uri": "https://api.scryfall.com/sets/ust",
                        "set_search_uri": "https://api.scryfall.com/cards/search?order=set\u0026q=e%3Aust\u0026unique=prints",
                        "scryfall_set_uri": "https://scryfall.com/sets/ust?utm_source=api",
                        "rulings_uri": "https://api.scryfall.com/cards/cb3587b9-e727-4f37-b4d6-1baa7316262f/rulings",
                        "prints_search_uri": "https://api.scryfall.com/cards/search?order=set\u0026q=%21%E2%80%9C%22Rumors+of+My+Death+.+.+.%22%E2%80%9D+include%3Aextras\u0026unique=prints",
                        "collector_number": "65", "digital": False, "rarity": "uncommon",
                        "watermark": "leagueofdastardlydoom",
                        "flavor_text": "By the fourth funeral, the mooks had gotten pretty good at them.",
                        "illustration_id": "f04b83e3-012a-473f-b2b1-876741c0645a", "artist": "Alex Konstad",
                        "frame": "2015", "full_art": False, "border_color": "silver", "timeshifted": False,
                        "colorshifted": False, "futureshifted": False, "story_spotlight": False, "related_uris": {
        "gatherer": "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=439454",
        "tcgplayer_decks": "https://decks.tcgplayer.com/magic/deck/search?contains=%22Rumors+of+My+Death+.+.+.%22\u0026page=1\u0026partner=Scryfall\u0026utm_campaign=affiliate\u0026utm_medium=scryfall\u0026utm_source=scryfall",
        "edhrec": "http://edhrec.com/route/?cc=%22Rumors+of+My+Death+.+.+.%22",
        "mtgtop8": "http://mtgtop8.com/search?MD_check=1\u0026SB_check=1\u0026cards=%22Rumors+of+My+Death+.+.+.%22"}}

MARKET_RESEARCH_SCRYFALL_DATA = {"object": "card", "id": "5c1f3f52-cb9b-4b2a-bb02-6175897ae76e",
                                 "oracle_id": "94a3b2af-0741-48c5-b827-6ff529bafae3", "multiverse_ids": [74237],
                                 "tcgplayer_id": 37906,
                                 "name": "Our Market Research Shows That Players Like Really Long Card Names So We Made this Card to Have the Absolute Longest Card Name Ever Elemental",
                                 "lang": "en",
                                 "uri": "https://api.scryfall.com/cards/5c1f3f52-cb9b-4b2a-bb02-6175897ae76e",
                                 "scryfall_uri": "https://scryfall.com/card/unh/107/our-market-research-shows-that-players-like-really-long-card-names-so-we-made-this-card-to-have-the-absolute-longest-card-name-ever-elemental?utm_source=api",
                                 "layout": "normal", "highres_image": True, "image_uris": {
        "small": "https://img.scryfall.com/cards/small/en/unh/107.jpg?1517813031",
        "normal": "https://img.scryfall.com/cards/normal/en/unh/107.jpg?1517813031",
        "large": "https://img.scryfall.com/cards/large/en/unh/107.jpg?1517813031",
        "png": "https://img.scryfall.com/cards/png/en/unh/107.png?1517813031",
        "art_crop": "https://img.scryfall.com/cards/art_crop/en/unh/107.jpg?1517813031",
        "border_crop": "https://img.scryfall.com/cards/border_crop/en/unh/107.jpg?1517813031"},
                                 "mana_cost": "{1}{G}{G}", "cmc": 3.0, "type_line": "Creature — Elemental",
                                 "oracle_text": "Art rampage 2 (Whenever this creature becomes blocked by a creature, it gets +2/+2 for each creature in the blocker's art beyond the first.)",
                                 "power": "2", "toughness": "2", "colors": ["G"], "color_identity": ["G"],
                                 "legalities": {"standard": "not_legal", "future": "not_legal", "frontier": "not_legal",
                                                "modern": "not_legal", "legacy": "not_legal", "pauper": "not_legal",
                                                "vintage": "not_legal", "penny": "not_legal", "commander": "not_legal",
                                                "1v1": "not_legal", "duel": "not_legal", "brawl": "not_legal"},
                                 "reserved": False, "foil": True, "nonfoil": True, "oversized": False, "reprint": False,
                                 "set": "unh", "set_name": "Unhinged", "set_uri": "https://api.scryfall.com/sets/unh",
                                 "set_search_uri": "https://api.scryfall.com/cards/search?order=set\u0026q=e%3Aunh\u0026unique=prints",
                                 "scryfall_set_uri": "https://scryfall.com/sets/unh?utm_source=api",
                                 "rulings_uri": "https://api.scryfall.com/cards/5c1f3f52-cb9b-4b2a-bb02-6175897ae76e/rulings",
                                 "prints_search_uri": "https://api.scryfall.com/cards/search?order=set\u0026q=%21%E2%80%9COur+Market+Research+Shows+That+Players+Like+Really+Long+Card+Names+So+We+Made+this+Card+to+Have+the+Absolute+Longest+Card+Name+Ever+Elemental%E2%80%9D+include%3Aextras\u0026unique=prints",
                                 "collector_number": "107", "digital": False, "rarity": "common",
                                 "flavor_text": "Just call it OMRSTPLRLCNSWMTCTHTALCNEE for short.",
                                 "illustration_id": "dd2a48ad-3c45-47e4-88f3-ab90b37c1e0e",
                                 "artist": "Greg Hildebrandt", "frame": "2003", "full_art": False,
                                 "border_color": "silver", "timeshifted": False, "colorshifted": False,
                                 "futureshifted": False, "story_spotlight": False, "related_uris": {
        "gatherer": "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74237",
        "tcgplayer_decks": "https://decks.tcgplayer.com/magic/deck/search?contains=Our+Market+Research+Shows+That+Players+Like+Really+Long+Card+Names+So+We+Made+this+Card+to+Have+the+Absolute+Longest+Card+Name+Ever+Elemental\u0026page=1\u0026partner=Scryfall\u0026utm_campaign=affiliate\u0026utm_medium=scryfall\u0026utm_source=scryfall",
        "edhrec": "http://edhrec.com/route/?cc=Our+Market+Research+Shows+That+Players+Like+Really+Long+Card+Names+So+We+Made+this+Card+to+Have+the+Absolute+Longest+Card+Name+Ever+Elemental",
        "mtgtop8": "http://mtgtop8.com/search?MD_check=1\u0026SB_check=1\u0026cards=Our+Market+Research+Shows+That+Players+Like+Really+Long+Card+Names+So+We+Made+this+Card+to+Have+the+Absolute+Longest+Card+Name+Ever+Elemental"}}

ULTIMATE_NIGHTMARE_SCRYFALL_DATA = {"object": "card", "id": "616abc97-4276-4e96-bbe8-e47ba7cac075",
                                    "oracle_id": "9adc9df1-bab0-4458-9453-7028f23693b8", "multiverse_ids": [9757],
                                    "tcgplayer_id": 910,
                                    "name": "The Ultimate Nightmare of Wizards of the Coast® Customer Service",
                                    "lang": "en",
                                    "uri": "https://api.scryfall.com/cards/616abc97-4276-4e96-bbe8-e47ba7cac075",
                                    "scryfall_uri": "https://scryfall.com/card/ugl/53/the-ultimate-nightmare-of-wizards-of-the-coast%C2%AE-customer-service?utm_source=api",
                                    "layout": "normal", "highres_image": True, "image_uris": {
        "small": "https://img.scryfall.com/cards/small/en/ugl/53.jpg?1517813031",
        "normal": "https://img.scryfall.com/cards/normal/en/ugl/53.jpg?1517813031",
        "large": "https://img.scryfall.com/cards/large/en/ugl/53.jpg?1517813031",
        "png": "https://img.scryfall.com/cards/png/en/ugl/53.png?1517813031",
        "art_crop": "https://img.scryfall.com/cards/art_crop/en/ugl/53.jpg?1517813031",
        "border_crop": "https://img.scryfall.com/cards/border_crop/en/ugl/53.jpg?1517813031"},
                                    "mana_cost": "{X}{Y}{Z}{R}{R}", "cmc": 2.0, "type_line": "Sorcery",
                                    "oracle_text": "The Ultimate Nightmare of Wizards of the Coast® Customer Service deals X damage to each of Y target creatures and Z target players or planeswalkers.",
                                    "colors": ["R"], "color_identity": ["R"],
                                    "legalities": {"standard": "not_legal", "future": "not_legal",
                                                   "frontier": "not_legal", "modern": "not_legal",
                                                   "legacy": "not_legal", "pauper": "not_legal", "vintage": "not_legal",
                                                   "penny": "not_legal", "commander": "not_legal", "1v1": "not_legal",
                                                   "duel": "not_legal", "brawl": "not_legal"}, "reserved": False,
                                    "foil": False, "nonfoil": True, "oversized": False, "reprint": False, "set": "ugl",
                                    "set_name": "Unglued", "set_uri": "https://api.scryfall.com/sets/ugl",
                                    "set_search_uri": "https://api.scryfall.com/cards/search?order=set\u0026q=e%3Augl\u0026unique=prints",
                                    "scryfall_set_uri": "https://scryfall.com/sets/ugl?utm_source=api",
                                    "rulings_uri": "https://api.scryfall.com/cards/616abc97-4276-4e96-bbe8-e47ba7cac075/rulings",
                                    "prints_search_uri": "https://api.scryfall.com/cards/search?order=set\u0026q=%21%E2%80%9CThe+Ultimate+Nightmare+of+Wizards+of+the+Coast%C2%AE+Customer+Service%E2%80%9D+include%3Aextras\u0026unique=prints",
                                    "collector_number": "53", "digital": False, "rarity": "uncommon",
                                    "flavor_text": "The number printed on the card is no longer in service. For help, go to wizards.custhelp.com or find us on Twitter @Wizards_Help.",
                                    "illustration_id": "a424fc78-8eec-4dfe-acbb-e180a334f405",
                                    "artist": "Melissa A. Benson", "frame": "1997", "full_art": False,
                                    "border_color": "silver", "timeshifted": False, "colorshifted": False,
                                    "futureshifted": False, "story_spotlight": False, "related_uris": {
        "gatherer": "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=9757",
        "tcgplayer_decks": "https://decks.tcgplayer.com/magic/deck/search?contains=The+Ultimate+Nightmare+of+Wizards+of+the+Coast%C2%AE+Customer+Service\u0026page=1\u0026partner=Scryfall\u0026utm_campaign=affiliate\u0026utm_medium=scryfall\u0026utm_source=scryfall",
        "edhrec": "http://edhrec.com/route/?cc=The+Ultimate+Nightmare+of+Wizards+of+the+Coast%C2%AE+Customer+Service",
        "mtgtop8": "http://mtgtop8.com/search?MD_check=1\u0026SB_check=1\u0026cards=The+Ultimate+Nightmare+of+Wizards+of+the+Coast%C2%AE+Customer+Service"}}

MISHRAS_FACTORY_SCRYFALL_DATA = {"object": "card", "id": "245cdc59-d560-4c10-b721-f51cc312e370",
                                 "oracle_id": "5963e0ef-e0bc-4611-ad4f-813a4c0eacfb", "multiverse_ids": [442231],
                                 "mtgo_id": 67398, "mtgo_foil_id": 67399, "tcgplayer_id": 161485,
                                 "name": "Mishra's Factory", "lang": "en",
                                 "uri": "https://api.scryfall.com/cards/245cdc59-d560-4c10-b721-f51cc312e370",
                                 "scryfall_uri": "https://scryfall.com/card/a25/242/mishras-factory?utm_source=api",
                                 "layout": "normal", "highres_image": True, "image_uris": {
        "small": "https://img.scryfall.com/cards/small/en/a25/242.jpg?1521726415",
        "normal": "https://img.scryfall.com/cards/normal/en/a25/242.jpg?1521726415",
        "large": "https://img.scryfall.com/cards/large/en/a25/242.jpg?1521726415",
        "png": "https://img.scryfall.com/cards/png/en/a25/242.png?1521726415",
        "art_crop": "https://img.scryfall.com/cards/art_crop/en/a25/242.jpg?1521726415",
        "border_crop": "https://img.scryfall.com/cards/border_crop/en/a25/242.jpg?1521726415"}, "mana_cost": "",
                                 "cmc": 0.0, "type_line": "Land",
                                 "oracle_text": "{T}: Add {C}.\n{1}: Mishra's Factory becomes a 2/2 Assembly-Worker artifact creature until end of turn. It's still a land.\n{T}: Target Assembly-Worker creature gets +1/+1 until end of turn.",
                                 "colors": [], "color_identity": [],
                                 "legalities": {"standard": "not_legal", "future": "not_legal", "frontier": "not_legal",
                                                "modern": "not_legal", "legacy": "legal", "pauper": "not_legal",
                                                "vintage": "legal", "penny": "not_legal", "commander": "legal",
                                                "1v1": "legal", "duel": "legal", "brawl": "not_legal"},
                                 "reserved": False, "foil": True, "nonfoil": True, "oversized": False, "reprint": True,
                                 "set": "a25", "set_name": "Masters 25", "set_uri": "https://api.scryfall.com/sets/a25",
                                 "set_search_uri": "https://api.scryfall.com/cards/search?order=set\u0026q=e%3Aa25\u0026unique=prints",
                                 "scryfall_set_uri": "https://scryfall.com/sets/a25?utm_source=api",
                                 "rulings_uri": "https://api.scryfall.com/cards/245cdc59-d560-4c10-b721-f51cc312e370/rulings",
                                 "prints_search_uri": "https://api.scryfall.com/cards/search?order=set\u0026q=%21%E2%80%9CMishra%27s+Factory%E2%80%9D+include%3Aextras\u0026unique=prints",
                                 "collector_number": "242", "digital": False, "rarity": "uncommon", "watermark": "set",
                                 "illustration_id": "40564d54-e98c-4c2b-8411-a84438c9cf5b", "artist": "Scott Chou",
                                 "frame": "2015", "full_art": False, "border_color": "black", "timeshifted": False,
                                 "colorshifted": False, "futureshifted": False, "story_spotlight": False,
                                 "edhrec_rank": 1945, "related_uris": {
        "gatherer": "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=442231",
        "tcgplayer_decks": "https://decks.tcgplayer.com/magic/deck/search?contains=Mishra%27s+Factory\u0026page=1\u0026partner=Scryfall\u0026utm_campaign=affiliate\u0026utm_medium=scryfall\u0026utm_source=scryfall",
        "edhrec": "http://edhrec.com/route/?cc=Mishra%27s+Factory",
        "mtgtop8": "http://mtgtop8.com/search?MD_check=1\u0026SB_check=1\u0026cards=Mishra%27s+Factory"}}

PLAINS_SCRYFALL_DATA = {"object": "card", "id": "93653b18-3821-485e-afeb-edafb0a9e84e",
                        "oracle_id": "bc71ebf6-2056-41f7-be35-b2e5c34afa99", "multiverse_ids": [455777],
                        "name": "Plains", "lang": "en",
                        "uri": "https://api.scryfall.com/cards/93653b18-3821-485e-afeb-edafb0a9e84e",
                        "scryfall_uri": "https://scryfall.com/card/gk1/100/plains?utm_source=api", "layout": "normal",
                        "highres_image": True, "image_uris": {
        "small": "https://img.scryfall.com/cards/small/front/9/3/93653b18-3821-485e-afeb-edafb0a9e84e.jpg?1541002853",
        "normal": "https://img.scryfall.com/cards/normal/front/9/3/93653b18-3821-485e-afeb-edafb0a9e84e.jpg?1541002853",
        "large": "https://img.scryfall.com/cards/large/front/9/3/93653b18-3821-485e-afeb-edafb0a9e84e.jpg?1541002853",
        "png": "https://img.scryfall.com/cards/png/front/9/3/93653b18-3821-485e-afeb-edafb0a9e84e.png?1541002853",
        "art_crop": "https://img.scryfall.com/cards/art_crop/front/9/3/93653b18-3821-485e-afeb-edafb0a9e84e.jpg?1541002853",
        "border_crop": "https://img.scryfall.com/cards/border_crop/front/9/3/93653b18-3821-485e-afeb-edafb0a9e84e.jpg?1541002853"},
                        "mana_cost": "", "cmc": 0.0, "type_line": "Basic Land — Plains",
                        "oracle_text": "({T}: Add {W}.)", "colors": [], "color_identity": ["W"],
                        "legalities": {"standard": "legal", "future": "legal", "frontier": "legal", "modern": "legal",
                                       "legacy": "legal", "pauper": "legal", "vintage": "legal", "penny": "legal",
                                       "commander": "legal", "1v1": "legal", "duel": "legal", "brawl": "legal"},
                        "reserved": False, "foil": False, "nonfoil": True, "oversized": False, "reprint": True,
                        "set": "gk1", "set_name": "GRN Guild Kit", "set_uri": "https://api.scryfall.com/sets/gk1",
                        "set_search_uri": "https://api.scryfall.com/cards/search?order=set\u0026q=e%3Agk1\u0026unique=prints",
                        "scryfall_set_uri": "https://scryfall.com/sets/gk1?utm_source=api",
                        "rulings_uri": "https://api.scryfall.com/cards/93653b18-3821-485e-afeb-edafb0a9e84e/rulings",
                        "prints_search_uri": "https://api.scryfall.com/cards/search?order=set\u0026q=%21%E2%80%9CPlains%E2%80%9D+include%3Aextras\u0026unique=prints",
                        "collector_number": "100", "digital": False, "rarity": "common", "watermark": "boros",
                        "illustration_id": "8f7df8a6-718d-4b3a-b907-4e0ed2be2e8c", "artist": "Yeong-Hao Han",
                        "frame": "2015", "full_art": False, "border_color": "black", "timeshifted": False,
                        "colorshifted": False, "futureshifted": False, "story_spotlight": False, "eur": "0.27",
                        "related_uris": {
                            "gatherer": "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=455777",
                            "tcgplayer_decks": "https://decks.tcgplayer.com/magic/deck/search?contains=Plains\u0026page=1\u0026partner=Scryfall\u0026utm_campaign=affiliate\u0026utm_medium=scryfall\u0026utm_source=scryfall",
                            "edhrec": "http://edhrec.com/route/?cc=Plains",
                            "mtgtop8": "http://mtgtop8.com/search?MD_check=1\u0026SB_check=1\u0026cards=Plains"},
                        "purchase_uris": {
                            "amazon": "https://www.amazon.com/gp/search?ie=UTF8\u0026index=toys-and-games\u0026keywords=Plains\u0026tag=scryfall-20",
                            "ebay": "http://rover.ebay.com/rover/1/711-53200-19255-0/1?campid=5337966903\u0026icep_catId=19107\u0026icep_ff3=10\u0026icep_sortBy=12\u0026icep_uq=Plains\u0026icep_vectorid=229466\u0026ipn=psmain\u0026kw=lg\u0026kwid=902099\u0026mtid=824\u0026pub=5575230669\u0026toolid=10001",
                            "tcgplayer": "https://shop.tcgplayer.com/productcatalog/product/show?ProductName=Plains\u0026partner=Scryfall\u0026utm_campaign=affiliate\u0026utm_medium=scryfall\u0026utm_source=scryfall",
                            "magiccardmarket": "https://www.cardmarket.com/en/Magic/Products/Singles/Guilds-of-Ravnica-Guild-Kits/Plains-Version-1?referrer=scryfall",
                            "cardmarket": "https://www.cardmarket.com/en/Magic/Products/Singles/Guilds-of-Ravnica-Guild-Kits/Plains-Version-1?referrer=scryfall",
                            "cardhoarder": "https://www.cardhoarder.com/cards?affiliate_id=scryfall\u0026data%5Bsearch%5D=Plains\u0026ref=card-profile\u0026utm_campaign=affiliate\u0026utm_medium=card\u0026utm_source=scryfall",
                            "card_kingdom": "https://www.cardkingdom.com/catalog/search?filter%5Bname%5D=Plains\u0026partner=scryfall\u0026utm_campaign=affiliate\u0026utm_medium=scryfall\u0026utm_source=scryfall",
                            "mtgo_traders": "http://www.mtgotraders.com/store/search.php?q=Plains\u0026referral=scryfall",
                            "coolstuffinc": "https://www.coolstuffinc.com/main_search.php?pa=searchOnName\u0026page=1\u0026q=Plains\u0026resultsPerPage=50\u0026utm_source=scryfall"}}

ARID_MESA_SCRYFALL_DATA = {"object": "card", "id": "c9a8cc61-7e36-4df7-9c89-c32fce129c5a",
                           "oracle_id": "c5acf2a5-40f4-433d-a74d-1cb56c521464", "multiverse_ids": [426054],
                           "mtgo_id": 63185, "mtgo_foil_id": 63186, "tcgplayer_id": 128275, "name": "Arid Mesa",
                           "lang": "en", "uri": "https://api.scryfall.com/cards/c9a8cc61-7e36-4df7-9c89-c32fce129c5a",
                           "scryfall_uri": "https://scryfall.com/card/mm3/229/arid-mesa?utm_source=api",
                           "layout": "normal", "highres_image": True,
                           "image_uris": {"small": "https://img.scryfall.com/cards/small/en/mm3/229.jpg?1535416221",
                                          "normal": "https://img.scryfall.com/cards/normal/en/mm3/229.jpg?1535416221",
                                          "large": "https://img.scryfall.com/cards/large/en/mm3/229.jpg?1535416221",
                                          "png": "https://img.scryfall.com/cards/png/en/mm3/229.png?1535416221",
                                          "art_crop": "https://img.scryfall.com/cards/art_crop/en/mm3/229.jpg?1535416221",
                                          "border_crop": "https://img.scryfall.com/cards/border_crop/en/mm3/229.jpg?1535416221"},
                           "mana_cost": "", "cmc": 0.0, "type_line": "Land",
                           "oracle_text": "{T}, Pay 1 life, Sacrifice Arid Mesa: Search your library for a Mountain or Plains card and put it onto the battlefield. Then shuffle your library.",
                           "colors": [], "color_identity": [],
                           "legalities": {"standard": "not_legal", "future": "not_legal", "frontier": "not_legal",
                                          "modern": "legal", "legacy": "legal", "pauper": "not_legal",
                                          "vintage": "legal", "penny": "not_legal", "commander": "legal",
                                          "1v1": "legal", "duel": "legal", "brawl": "not_legal"}, "reserved": False,
                           "foil": True, "nonfoil": True, "oversized": False, "reprint": True, "set": "mm3",
                           "set_name": "Modern Masters 2017", "set_uri": "https://api.scryfall.com/sets/mm3",
                           "set_search_uri": "https://api.scryfall.com/cards/search?order=set\u0026q=e%3Amm3\u0026unique=prints",
                           "scryfall_set_uri": "https://scryfall.com/sets/mm3?utm_source=api",
                           "rulings_uri": "https://api.scryfall.com/cards/c9a8cc61-7e36-4df7-9c89-c32fce129c5a/rulings",
                           "prints_search_uri": "https://api.scryfall.com/cards/search?order=set\u0026q=%21%E2%80%9CArid+Mesa%E2%80%9D+include%3Aextras\u0026unique=prints",
                           "collector_number": "229", "digital": False, "rarity": "rare",
                           "illustration_id": "c27f39e0-315a-434b-8542-46791fbbd42a", "artist": "Raymond Swanland",
                           "frame": "2015", "full_art": False, "border_color": "black", "timeshifted": False,
                           "colorshifted": False, "futureshifted": False, "story_spotlight": False, "edhrec_rank": 155,
                           "usd": "37.29", "eur": "28.77", "tix": "6.00", "related_uris": {
        "gatherer": "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=426054",
        "tcgplayer_decks": "https://decks.tcgplayer.com/magic/deck/search?contains=Arid+Mesa\u0026page=1\u0026partner=Scryfall\u0026utm_campaign=affiliate\u0026utm_medium=scryfall\u0026utm_source=scryfall",
        "edhrec": "http://edhrec.com/route/?cc=Arid+Mesa",
        "mtgtop8": "http://mtgtop8.com/search?MD_check=1\u0026SB_check=1\u0026cards=Arid+Mesa"}, "purchase_uris": {
        "amazon": "https://www.amazon.com/gp/search?ie=UTF8\u0026index=toys-and-games\u0026keywords=Arid+Mesa\u0026tag=scryfall-20",
        "ebay": "http://rover.ebay.com/rover/1/711-53200-19255-0/1?campid=5337966903\u0026icep_catId=19107\u0026icep_ff3=10\u0026icep_sortBy=12\u0026icep_uq=Arid+Mesa\u0026icep_vectorid=229466\u0026ipn=psmain\u0026kw=lg\u0026kwid=902099\u0026mtid=824\u0026pub=5575230669\u0026toolid=10001",
        "tcgplayer": "https://shop.tcgplayer.com/magic/modern-masters-2017/arid-mesa?partner=Scryfall\u0026utm_campaign=affiliate\u0026utm_medium=scryfall\u0026utm_source=scryfall",
        "magiccardmarket": "https://www.cardmarket.com/en/Magic/Products/Singles/Modern-Masters-2017/Arid-Mesa?referrer=scryfall",
        "cardmarket": "https://www.cardmarket.com/en/Magic/Products/Singles/Modern-Masters-2017/Arid-Mesa?referrer=scryfall",
        "cardhoarder": "https://www.cardhoarder.com/cards/63185?affiliate_id=scryfall\u0026ref=card-profile\u0026utm_campaign=affiliate\u0026utm_medium=card\u0026utm_source=scryfall",
        "card_kingdom": "https://www.cardkingdom.com/catalog/search?filter%5Bname%5D=Arid+Mesa\u0026partner=scryfall\u0026utm_campaign=affiliate\u0026utm_medium=scryfall\u0026utm_source=scryfall",
        "mtgo_traders": "http://www.mtgotraders.com/deck/ref.php?id=63185\u0026referral=scryfall",
        "coolstuffinc": "https://www.coolstuffinc.com/main_search.php?pa=searchOnName\u0026page=1\u0026q=Arid+Mesa\u0026resultsPerPage=50\u0026utm_source=scryfall"}}

GIDEON_SCRYFALL_DATA = {"object": "card", "id": "187e887c-c39d-4d25-a506-cdc95fc70316",
                        "oracle_id": "51eae7ff-fed9-4afe-8053-7690379449dd", "multiverse_ids": [401897],
                        "mtgo_id": 58317, "mtgo_foil_id": 58318, "tcgplayer_id": 104271,
                        "name": "Gideon, Ally of Zendikar", "lang": "en",
                        "uri": "https://api.scryfall.com/cards/187e887c-c39d-4d25-a506-cdc95fc70316",
                        "scryfall_uri": "https://scryfall.com/card/bfz/29/gideon-ally-of-zendikar?utm_source=api",
                        "layout": "normal", "highres_image": True,
                        "image_uris": {"small": "https://img.scryfall.com/cards/small/en/bfz/29.jpg?1517813031",
                                       "normal": "https://img.scryfall.com/cards/normal/en/bfz/29.jpg?1517813031",
                                       "large": "https://img.scryfall.com/cards/large/en/bfz/29.jpg?1517813031",
                                       "png": "https://img.scryfall.com/cards/png/en/bfz/29.png?1517813031",
                                       "art_crop": "https://img.scryfall.com/cards/art_crop/en/bfz/29.jpg?1517813031",
                                       "border_crop": "https://img.scryfall.com/cards/border_crop/en/bfz/29.jpg?1517813031"},
                        "mana_cost": "{2}{W}{W}", "cmc": 4.0, "type_line": "Legendary Planeswalker — Gideon",
                        "oracle_text": "+1: Until end of turn, Gideon, Ally of Zendikar becomes a 5/5 Human Soldier Ally creature with indestructible that's still a planeswalker. Prevent all damage that would be dealt to him this turn.\n0: Create a 2/2 white Knight Ally creature token.\n−4: You get an emblem with \"Creatures you control get +1/+1.\"",
                        "loyalty": "4", "colors": ["W"], "color_identity": ["W"], "all_parts": [
        {"object": "related_card", "id": "187e887c-c39d-4d25-a506-cdc95fc70316", "name": "Gideon, Ally of Zendikar",
         "uri": "https://api.scryfall.com/cards/bfz/29"},
        {"object": "related_card", "id": "0419a202-6e32-4f0a-a032-72f6c00cae5e", "name": "Knight Ally",
         "uri": "https://api.scryfall.com/cards/tbfz/5"},
        {"object": "related_card", "id": "cd8be597-f402-4fb0-9135-897c4a0946f6",
         "name": "Gideon, Ally of Zendikar Emblem", "uri": "https://api.scryfall.com/cards/tbfz/12"}],
                        "legalities": {"standard": "not_legal", "future": "not_legal", "frontier": "legal",
                                       "modern": "legal", "legacy": "legal", "pauper": "not_legal", "vintage": "legal",
                                       "penny": "not_legal", "commander": "legal", "1v1": "legal", "duel": "legal",
                                       "brawl": "not_legal"}, "reserved": False, "foil": True, "nonfoil": True,
                        "oversized": False, "reprint": False, "set": "bfz", "set_name": "Battle for Zendikar",
                        "set_uri": "https://api.scryfall.com/sets/bfz",
                        "set_search_uri": "https://api.scryfall.com/cards/search?order=set\u0026q=e%3Abfz\u0026unique=prints",
                        "scryfall_set_uri": "https://scryfall.com/sets/bfz?utm_source=api",
                        "rulings_uri": "https://api.scryfall.com/cards/187e887c-c39d-4d25-a506-cdc95fc70316/rulings",
                        "prints_search_uri": "https://api.scryfall.com/cards/search?order=set\u0026q=%21%E2%80%9CGideon%2C+Ally+of+Zendikar%E2%80%9D+include%3Aextras\u0026unique=prints",
                        "collector_number": "29", "digital": False, "rarity": "mythic",
                        "illustration_id": "3f8e9d1c-8d81-43fc-96d1-86b5277c9b8d", "artist": "Eric Deschamps",
                        "frame": "2015", "full_art": False, "border_color": "black", "timeshifted": False,
                        "colorshifted": False, "futureshifted": False, "story_spotlight": False, "edhrec_rank": 1619,
                        "usd": "6.58", "eur": "8.37", "tix": "2.77", "related_uris": {
        "gatherer": "http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=401897",
        "tcgplayer_decks": "https://decks.tcgplayer.com/magic/deck/search?contains=Gideon%2C+Ally+of+Zendikar\u0026page=1\u0026partner=Scryfall\u0026utm_campaign=affiliate\u0026utm_medium=scryfall\u0026utm_source=scryfall",
        "edhrec": "http://edhrec.com/route/?cc=Gideon%2C+Ally+of+Zendikar",
        "mtgtop8": "http://mtgtop8.com/search?MD_check=1\u0026SB_check=1\u0026cards=Gideon%2C+Ally+of+Zendikar"},
                        "purchase_uris": {
                            "amazon": "https://www.amazon.com/gp/search?ie=UTF8\u0026index=toys-and-games\u0026keywords=Gideon%2C+Ally+of+Zendikar\u0026tag=scryfall-20",
                            "ebay": "http://rover.ebay.com/rover/1/711-53200-19255-0/1?campid=5337966903\u0026icep_catId=19107\u0026icep_ff3=10\u0026icep_sortBy=12\u0026icep_uq=Gideon%2C+Ally+of+Zendikar\u0026icep_vectorid=229466\u0026ipn=psmain\u0026kw=lg\u0026kwid=902099\u0026mtid=824\u0026pub=5575230669\u0026toolid=10001",
                            "tcgplayer": "https://shop.tcgplayer.com/magic/battle-for-zendikar/gideon-ally-of-zendikar?partner=Scryfall\u0026utm_campaign=affiliate\u0026utm_medium=scryfall\u0026utm_source=scryfall",
                            "magiccardmarket": "https://www.cardmarket.com/en/Magic/Products/Singles/Battle-for-Zendikar/Gideon-Ally-of-Zendikar?referrer=scryfall",
                            "cardmarket": "https://www.cardmarket.com/en/Magic/Products/Singles/Battle-for-Zendikar/Gideon-Ally-of-Zendikar?referrer=scryfall",
                            "cardhoarder": "https://www.cardhoarder.com/cards/58317?affiliate_id=scryfall\u0026ref=card-profile\u0026utm_campaign=affiliate\u0026utm_medium=card\u0026utm_source=scryfall",
                            "card_kingdom": "https://www.cardkingdom.com/catalog/search?filter%5Bname%5D=Gideon%2C+Ally+of+Zendikar\u0026partner=scryfall\u0026utm_campaign=affiliate\u0026utm_medium=scryfall\u0026utm_source=scryfall",
                            "mtgo_traders": "http://www.mtgotraders.com/deck/ref.php?id=58317\u0026referral=scryfall",
                            "coolstuffinc": "https://www.coolstuffinc.com/main_search.php?pa=searchOnName\u0026page=1\u0026q=Gideon%2C+Ally+of+Zendikar\u0026resultsPerPage=50\u0026utm_source=scryfall"}}

MESA_ORACLE_TEXT = '{T}, Pay 1 life, Sacrifice Arid Mesa: Search your library for a Mountain or Plains card and put it onto the battlefield. Then shuffle your library.'
FACTORY_ORACLE_TEXT = "{T}: Add {C}.\n{1}: Mishra's Factory becomes a 2/2 Assembly-Worker artifact creature until end of turn. It's still a land.\n{T}: Target Assembly-Worker creature gets +1/+1 until end of turn."
GIDEON_ORACLE_TEXT = '+1: Until end of turn, Gideon, Ally of Zendikar becomes a 5/5 Human Soldier Ally creature with indestructible that\'s still a planeswalker. Prevent all damage that would be dealt to him this turn.\n0: Create a 2/2 white Knight Ally creature token.\n−4: You get an emblem with "Creatures you control get +1/+1."'
