# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_catalog', '0003_auto_20181107_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scryfallcard',
            name='image_url',
        ),
    ]
