# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScryfallCard',
            fields=[
                ('oracle_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('mana_cost', models.CharField(blank=True, max_length=128, null=True)),
                ('cmc', models.IntegerField(blank=True, null=True)),
                ('types', models.CharField(blank=True, max_length=256, null=True)),
                ('subtypes', models.CharField(blank=True, max_length=256, null=True)),
                ('colors', models.CharField(blank=True, max_length=128, null=True)),
                ('color_identity', models.CharField(blank=True, max_length=128, null=True)),
                ('oracle_text', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
    ]
