# Generated by Django 2.2 on 2019-04-04 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_catalog', '0008_auto_20190404_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_catalog.CardSet'),
        ),
        migrations.AlterField(
            model_name='cardprice',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_catalog.Card'),
        ),
    ]
