# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_catalog', '0004_remove_scryfallcard_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cmc',
            field=models.IntegerField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='scryfallcard',
            name='cmc',
            field=models.IntegerField(blank=True, max_length=128, null=True),
        ),
    ]
