# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 17:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_catalog', '0006_auto_20181113_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2019, 1, 16))),
                ('low', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('mid', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('market', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('foil_low', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('foil_mid', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('foil_high', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('foil_market', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_catalog.Card')),
            ],
        ),
    ]
